### ISSUE TITLE
[Feature Request] Small player cart

### ISSUE THREAD

**Issue by xR4YM0ND** [jmb05/nifty-carts#1]
Could you add a small cart (with chest or without) that only the player can tow.

Inspiration comes from the Game ECO

![image](https://github.com/jmb05/nifty-carts/assets/97298005/be97c830-7055-43e3-8549-e4bfa7170970)

Space of 1 Chest or so

**Comment by jmb05** [comment]
This mod was originally only made as a port of the AstikorCarts mod, but I might consider adding this in the future

**Comment by DcNdrew** [comment]
I vote for it!
An option would be awesome if the player can pull the cart too. As I remember older versions of AstikorCarts let it.

**Comment by xR4YM0ND** [comment]
Thank yooouuu !
