### ISSUE TITLE
[question/request] Player pulling for 1.20.1

### ISSUE THREAD

**Issue by SilveroGhost** [jmb05/nifty-carts#10]
Hello! This mod is absolutely wonderful one of the best transportation + storage mod's ive seen in a while that gives actual interaction to the world. And I was wondering if it's at all possible for the player pulling feature from the newer updates to be made for the 1.20.1 version of the mod. If not I understand the mods amazing regardless, thank you :>

**Comment by jmb05** [comment]
Is currently being worked on

**Comment by jmb05** [comment]
Fixed in 3.0.1+1.20.1
