### ISSUE TITLE
Pulling carts while flying elytra

### ISSUE THREAD

**Issue by ykvox** [jmb05/nifty-carts#11]
Hi ! 
i'm wondering where in the code could i change that carts are let go with gravity/encountering an obstacle ?
(for a map purpose i'd like players to elytra flight with carts)

thank you in advance, i wish you well !

**Comment by ykvox** [comment]
![2024-03-09 020232](https://github.com/jmb05/nifty-carts/assets/61479000/102c2310-99ab-437d-9398-971c7b36114f)
just realized nbt {NoGravity:1b} does work, but then it also loses the ground gravity

(side note: i just LOVE how the wheels still spin mid air)

**Comment by jmb05** [comment]
Unfortunately this seems pretty complicated and flying with an attached cart is not the intended use case.

**Comment by ykvox** [comment]
it's okay, i made a datapack that detects when you have elytra on and are flying, switching the gravity of the cart off and on

thanks anyway !
