### ISSUE TITLE
incompatibility with modded armour

### ISSUE THREAD

**Issue by cole3050** [jmb05/nifty-carts#12]
I use a mod called "epic knights" it changes how the vanilla armour models work to allow for decorations to be added to them,
this causes an issue where placing any of the vanilla armour into a supply cart will crash the game and soft lock the world/save.

simplest solution in my opinion would be a config option to disable the armour rending in the the cart.

**Comment by jmb05** [comment]
I can't recreate the crash. Which version are you using?

**Comment by cole3050** [comment]
I just checked and this seems to have been fixxed in the newer version on 1.20.1
