### ISSUE TITLE
Make it possible for plows to destroy flowers and tall grass.

### ISSUE THREAD

**Issue by Squ-Cog** [jmb05/nifty-carts#13]
Currently when making paths or farms with the plow, only grass blocks with an empty space will convert. It would be great if grass blocks with other plants on them would convert too and destroy the block above. This way paths won't look so ugly and making farms is a lot easier.

**Comment by jmb05** [comment]
Added in versions 3.3.1+1.20.4 and 3.0.2+1.20.1
