### ISSUE TITLE
Plow cart donesn't work below height 1

### ISSUE THREAD

**Issue by Zano1999** [jmb05/nifty-carts#17]
When the plow is equipped with some tools and is lowered it does not generate changes to the terrain.

![image](https://github.com/jmb05/nifty-carts/assets/42555362/4daed7a3-fa47-494a-a617-87587acdb236)

**Comment by jmb05** [comment]
Which tools are in the plow?

**Comment by Zano1999** [comment]
Tried with iron hoes and shovels

**Comment by jmb05** [comment]
I cannot reproduce your issue. Which version are you using? Is the plow being pulled? It only changes the terrain if it is moving.

**Comment by Zano1999** [comment]
3.0.1+1.20.1

**Comment by jmb05** [comment]
Does you still have this issue in the version 3.0.2+1.20.1 ?

**Comment by Zano1999** [comment]
Yes

**Comment by jmb05** [comment]
This seems to be happening when the plow is at negative height which is why it shows up in your superflat world. It should work if you are at y-level 1 or higher. But I will try to figure out how to fix this.
