### ISSUE TITLE
Client-sided crash with supply carts.

### ISSUE THREAD

**Issue by iacuobos** [jmb05/nifty-carts#19]
Client-sided crash.
Mainly using supply carts.
does not crash on server-side. seems to be rendering related.

**Comment by iacuobos** [comment]
[crash-2024-04-22_00.13.24-client.txt](https://github.com/jmb05/nifty-carts/files/15055274/crash-2024-04-22_00.13.24-client.txt)

**Comment by jmb05** [comment]
This seems like an incompatibility with Iris. Unfortunately I don't have much time for modding at the moment. So the fix will take a while.

**Comment by jmb05** [comment]
It also seems you are using Quilt. I do not use Quilt and I don't test with it so I cannot guarantee that this mod is compatible with Quilt.

**Comment by iacuobos** [comment]
Hey! I was able to fix it by disabling armor rendering, temporarily, solving the crash at least client-side

**Comment by jmb05** [comment]
Upon further inspection this seems to be indeed an incompatibility with the Quilt Loader. I do not use Quilt and don't test the mod against it. Which means if no one else contributes a fix, this issue will unfortunately persist. But I will add configuration options to disable the rendering of the armor which should serve as a workaround.
