### ISSUE TITLE
[Port Request]

### ISSUE THREAD

**Issue by Mossy-Skies** [jmb05/nifty-carts#2]
Would it be possible for you to port this to 1.19.2? I understand if not!

**Comment by cyelis1224** [comment]
I second this, I really want this mod on 1.19.2 so I can use it with conquest refabricated. its pretty much a must have to have some kind of cart system for how much new content is in that mod. it was great to have in the older versions. I tried to port it myself and got it to launch with no errors, but none of the carts are in the creative item inventory so I'm not sure what's not working. There is a 1.19.2 version of the original mod but its for forge. >.>

**Comment by Pilgrim54** [comment]
I agree, this would make my conquest refabricated world complete. Thanks for the hard work you put in porting this mod to fabric in the first place.

**Comment by cyelis1224** [comment]
on a side note @Pilgrim54 , i just realized there is grim's transportables for 1.19.2 but i dont like it as much as this one.

**Comment by Pilgrim54** [comment]
@cyelis1224 I just checked out grim's transportables and I don't like it at all. This one is much better by far.

**Comment by benio1394** [comment]
I would like to ask about it too. 1.19.2 hava currently the most mods to choose, so that will boost usage of your mod

**Comment by LyricalOnyrical** [comment]
Hi there - I'd also love for this mod to be ported to 1.19.2, I currently am playing with other mods that make other modes of transportation different from the elytra better and this one would also fit very well :)

**Comment by jmb05** [comment]
Sorry for taking so long. I have now ported the mod to 1.19.2:
- Modrinth: https://modrinth.com/mod/niftycarts/version/2.1.0+1.19.2
- Github: https://github.com/jmb05/nifty-carts/releases/tag/2.1.0%2B1.19.2
- CurseForge: https://www.curseforge.com/minecraft/mc-mods/niftycarts/files/4890555

**Comment by Pilgrim54** [comment]
Thanks so much for porting it to 1.19.2. It was worth the wait.
