### ISSUE TITLE
Jockey Skeleton Horses (and other abstract mobs that are mounted) cannot move

### ISSUE THREAD

**Issue by iacuobos** [jmb05/nifty-carts#21]
Title, seems to be due to the mixin, i'll check if i can fix it on my side.

**Comment by jmb05** [comment]
I'm not sure what you mean. Which Version are you using? And which cart?

**Comment by iacuobos** [comment]
Latest quilt version, could reproduce in fabric, if you spawn a entity mounted on a mob they cannot move

**Comment by iacuobos** [comment]
Reproduced behaviour in a fabric dev env.


https://streamable.com/yizy3e

**Comment by jmb05** [comment]
This is a weird one. I am having trouble finding the exact cause of the bug if anyone could help finding the cause that would be highly appreciated.

**Comment by iacuobos** [comment]
Seems to be related to some of the mixins, as disabling them permits normal mob behaviour
