### ISSUE TITLE
Modded Animal Cart Support

### ISSUE THREAD

**Issue by 533kr** [jmb05/nifty-carts#22]
Would it be possible to add a config element to change what animals are able to be hauled using the animal cart? I'm playing using the [Doggy Talents Next](https://modrinth.com/mod/doggy-talents-next) mod, but once a dog has been converted to the modded version using a training treat, the animal cart can no longer pick it up. I'm not sure how difficult that would be to implement, but if it's possible, the option would be lovely!

**Comment by jmb05** [comment]
Every Land Mob can sit in the Animal Cart if the Mob is not too large. This seems to be because Doggy Talents doesn't allow dogs to mount other entities.
