### ISSUE TITLE
[2 Feature Requests] Crop Harvester & Mower

### ISSUE THREAD

**Issue by Rhett008** [jmb05/nifty-carts#23]
Hello, loving the mod. It's very useful for moving around villager slaves.
I'd like to request either 1 or both of the following carts be added to the mod.
Pictures attached for imaginative reference.

### Harvester

Cart driven by horse for harvesting crops based on old real-life technology.
- 2-3 blocks harvesting width
- Can only be operated and moved using a horse, cannot be moved by hand, but can still be broken and placed
- Crafted using a new 'blade' item crafted around a wheel for the harvesting blade (probably made from iron)

![image](https://github.com/jmb05/nifty-carts/assets/160710805/46e9244c-0cb0-4a89-a1cd-e1b56556c708)
![image](https://github.com/jmb05/nifty-carts/assets/160710805/990bd0dd-2557-4977-bad0-a9eab436dc28)

### Mower

Cart for mowing down grass, flowers, pink petals, etc. without destroying or tilling ground.
- 1-3 blocks mowing width
- Can be moved by horse or hand like current carts
- Crafted using new 'blade' item

![image](https://github.com/jmb05/nifty-carts/assets/160710805/cf4e5ad1-bad5-433e-8307-7c39b404367a)

Thanks for your work and consideration

**Comment by jmb05** [comment]
These look like cool concepts but they don't really fit with my vision for the mod. I would like to keep the mod more rustic and medieval and these concepts are too modern.
