### ISSUE TITLE
Server with Quilt

### ISSUE THREAD

**Issue by SicuramenteDave** [jmb05/nifty-carts#27]
When I try to start the server, it crash with this log:

---- Quilt Loader: Failed to load ----
Date/Time: 2024/05/11 11:22:58.6539
Quilt Loader Version: 0.23.1

-- Error 1 --

NiftyCarts requires version [0.15.7, âˆž) of fabricloader, which is missing!

- <mods>/niftycarts-3.0.2+1.20.1.jar

-- Plugin State --

Cycle number = 1
Cycle Step = SOLVE

Loaded Plugins (2):
 - 'quilt_loader' (Builtin)
 - 'quilted_fabric_loader' (Builtin)

How can I fix this error?

**Comment by jmb05** [comment]
Please do note that this mod currently does not support the Quilt Loader so you may run into more issues. But this just seems to be that you Quilt Loader is out of date. Reinstalling the server with a newer Quilt version should do the trick (I tried with 0.25.0).
