### ISSUE TITLE
Crashes when moving an item into a cart

### ISSUE THREAD

**Issue by DRAGONTOS** [jmb05/nifty-carts#28]
**Describe the bug**
it crashed when I tried to move an item in a cart that was attached to a skeleton horse.

**To Reproduce**
1. Launch Minecraft
2. Enter the server
3. Crash

**Expected behavior**
To join the server and not crash.

**Log/Screenshots**
Client:
[reportlog.txt](https://github.com/jmb05/nifty-carts/files/15365935/reportlog.txt)
Server:
![reportlog](https://github.com/jmb05/nifty-carts/assets/46651680/020ae15e-c22c-4777-b29a-1e38100d5f99)

**Additional Information:**
 - Version: [1.20.1]
 - Modpack: https://git.kaleyfischer.xyz/DRAGONTOS/SMP-MODPACK.git
 - only in Multiplayer cus Singleplayer is broken in my modpack.

**Comment by jmb05** [comment]
This is a known issue with quilt when putting armor in the supply cart. I am currently not actively supporting quilt so you'll have to use the workaround of disabling the rendering of armor via the client-side config of the mod.
