### ISSUE TITLE
Allow players pulling carts

### ISSUE THREAD

**Issue by ChooChoo4** [jmb05/nifty-carts#3]
Hi, I just downloaded your mod from curseforge, but I met a bug when I pressed R I can't attach the cart on myself (in astikorcart I can attach the cart on myself) and there is no key conflict. I am using fabric 0.15.3 and fabric API 0.91.2.

**Comment by MrHotten** [comment]
Good afternoon, I have the same problem.
As I read in the comments and discussions of the original AstikorCarts mod, I was able to understand that there in the config you need to add the `minecraft:player` parameter to the list of allowed mobs.
But in this mod, I could not find a config to add this parameter.

**Comment by rabbit-time** [comment]
@MrHotten The list of allowed mobs is set to all by default, so there's no need to change this.

I'm also experiencing this bug and cannot pick up the carts for some reason.

@ChooChoo4 By any chance, could you provide a list of all mods you're using?

**Comment by MrHotten** [comment]
@rabbit-time Yes, by this time I had already studied the configuration file enough. But still it bothers me that I can't carry carts by myself without the help of a horse.

**Comment by jmb05** [comment]
This is now implemented in 3.1.1+1.20.2 and 3.0.1+1.20.1 the older Minecraft versions will soon follow
