### ISSUE TITLE
Preventing the cart from disconnecting from horse

### ISSUE THREAD

**Issue by Zeptm** [jmb05/nifty-carts#32]
The cart disconnects from a horse that jumps high, and another problem is when using the Horse Buff mod by CodeF53 that lets horses swim through water, the cart sinks and disconnects from the horse. This prevents any horse from crossing rivers when exploring with my horse.
*see images below*
![image](https://github.com/jmb05/nifty-carts/assets/172594479/97a3d50e-c3f9-4f5a-9242-c9c1f043a8fd)
![image](https://github.com/jmb05/nifty-carts/assets/172594479/49714236-35d8-40aa-b1fe-a64e61a4f849)

**Comment by jmb05** [comment]
Well, from my point of view it wouldn't make sense if carts could swim and maybe there should be some drawbacks when using carts. But I might make it optional so you can enable it in the config.

**Comment by Zeptm** [comment]
That would be highly appreciated, thanks!
