### ISSUE TITLE
[Sever crashed] Exception in server tick loop  java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_24828()" because "this.pulling" is null

### ISSUE THREAD

**Issue by UnnamedWei** [jmb05/nifty-carts#33]
Server crashed after something about the niftycarts happened

[crash-2024-07-05_21.59.47-server.txt](https://github.com/user-attachments/files/16112977/crash-2024-07-05_21.59.47-server.txt)

**Comment by jmb05** [comment]
I need more information. Are you using it with other mods. How does the crash happen? Can you reproduce it with only niftycarts installed?

**Comment by deli73** [comment]
This happened on our server while spamming the action key next to a supply cart, on 1.20.1. Hopefully that helps narrow it down.

**Comment by UnnamedWei** [comment]
Seems it happened when someone in the claim of Open Parties And Claims mod and try to use the carts

**Comment by jmb05** [comment]
I still can't reproduce this crash. I can use a cart in someone else's claim without a problem. (Only problem being that you probably shouldn't be able to use a cart in someones claim.) Under which specific conditions does it crash?
