### ISSUE TITLE
Build for 1.21 

### ISSUE THREAD

**Issue by dylanparry** [jmb05/nifty-carts#34]
Hi. Thanks for all your work on this mod, it's awesome :D Would it be possible to get a new build for 1.21? Thanks again.

**Comment by jmb05** [comment]
That is planned, but it is going to take a few weeks because I don't have much time currently.

**Comment by vico93** [comment]
Any news about it?

**Comment by grale730** [comment]
Hi any news?

**Comment by jmb05** [comment]
Is in the work, should be released shortly

**Comment by jmb05** [comment]
Version 21.0.0 for Minecraft 1.21 and 1.21.1 is now available on Modrinth and should be on CurseForge shortly

**Comment by vico93** [comment]
@jmb05 unfortunately nifty cards haven't marked Fabric Loader 0.16.5 as compatible on 1.21.1!

` Mod 'NiftyCarts' (niftycarts) 21.0.0 requires version 0.16.5 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.16.4!`

**Comment by jmb05** [comment]
@vico93 no, this means that Nifty Carts requires the Fabric Loader version 0.16.5 but you are still using 0.16.4

**Comment by vico93** [comment]
@jmb05 sorry, i thought it was the opposite case. (nifty requiring a lesser Fabric version).
