### ISSUE TITLE
REI does not show the crafting recipe. Also the crafting recipe itself doesn't work in survival

### ISSUE THREAD

**Issue by Tiramizuy** [jmb05/nifty-carts#37]
**Crafting Recipe does not work**
When trying to craft any of the items, it doesn't allow me to, I can access the materials and item itself through the creative inventory but I am unable to craft anything using them

**To Reproduce**
1. Just try to craft any item

**Expected behavior**
I thought the crafting recipe would work in survival or creative. Also I thought REI would show the crafting recipe

**Screenshots**
<img width="959" alt="image" src="https://github.com/user-attachments/assets/b152fb42-cb2e-471d-a919-73c5f4c12630">

**Additional Information:**
 - Version [Mod version 21.0.0+1.21]
 - Single Player
 - Using Fabric 16.5

**Comment by jmb05** [comment]
Fixed in 21.0.1
