### ISSUE TITLE
1.20.2 connecting carts on server disconnects other players

### ISSUE THREAD

**Issue by Pawlyssum** [jmb05/nifty-carts#4]
connecting a cart to a horse forces all players in the area, except for the one on the horse to disconnect from the server with this error: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 0, cap: 256)

**Comment by jmb05** [comment]
I cannot reproduce this behavior. Could you post your logs? Are you playing with other mods?
