### ISSUE TITLE
Placing Flowers in the hand cart crashes game

### ISSUE THREAD

**Issue by skeppp** [jmb05/nifty-carts#41]
Placing Flowers in the hand cart causes the game to hard crash and makes the world unloadable.  

I am using Niftycarts version 20.1.3 and fabric version 0.16.7 and no other mods.

**Comment by jmb05** [comment]
I need more information, i.e. a crash report. A possible workaround would be disabling render_supply_flowers in the client config.

**Comment by jmb05** [comment]
This is probably duplicate of #39
