### ISSUE TITLE
Client crashes when adding armor to a supply cart (1.19.2)

### ISSUE THREAD

**Issue by LyricalOnyrical** [jmb05/nifty-carts#5]
When attempting to add an enchanted diamond leggings to a supply cart, client crashes. Had to kill the cart entity in order to join the server again. Running niftycarts-2.1.0+1.19.2.jar, in 1.19.2 with Fabric Loader Version 0.14.25. 

Crash report: https://mclo.gs/hUV5e1M

**Comment by jmb05** [comment]
I cannot reproduce this crash
