### ISSUE TITLE
Incompatibility with Mythic Mounts

### ISSUE THREAD

**Issue by Skuldafn0** [jmb05/nifty-carts#6]
Hello,
When loading this mod (3.0.0) with Mythic Mounts (v7.4), the flying functionality of said mounts seems to break. Pressing the spacebar lunges them forward, but they do not stay afloat as they normally would. The flying mounts also do not move up and down depending on where you look.

I have tried excluding them by editing the configuration file to only accept horses but the broken flying issue remains. If this is not something on your end, then I apologize for the intrusion. 

The mod itself is high quality and convenient, and the models look awesome. I can't pick between both mods!

Thank you!

**Comment by jmb05** [comment]
Unfortunately Mythic Mounts is closed source. That makes this issue hard for me to track down and fix. So I will probably not fix this.
