### ISSUE TITLE
[Port Request] 1.17.1

### ISSUE THREAD

**Issue by linusvdv** [jmb05/nifty-carts#7]
Thanks for the great mod.
Would it be possible to port this mod to 1.17.1. I tried to do it myself for 3 - 4 hours but I am not experienced in Minecraft modding. I was rewrite the mod do use the older version of forge-config-api-port-fabric. But I didn't get Minecraft running.
Thank you in advance.

**Comment by jmb05** [comment]
I might consider it at some point but it is not a priority right now.
