### ISSUE TITLE
[1.20.1] Config file does not recognize "minecraft:player" as an entity.

### ISSUE THREAD

**Issue by syxht** [jmb05/nifty-carts#9]
Can't pull cart manually.

**Comment by DcNdrew** [comment]
Astikor Carts had this option AFAIK.

**Comment by syxht** [comment]
> Astikor Carts had this option AFAIK.

Yea, but since this is a direct port of the mod I would have assumed that NiftyCarts would also recognize "minecraft:player" like AstikorCarts does.

**Comment by jmb05** [comment]
Players can now pull carts in 3.0.1+1.20.1
